version: "3.9"

services:
  seed-express-backend:
    container_name: seed-express-backend
    image: seed-express-backend
    volumes:
      - type: bind
        source: .
        target: /app/seed-express-backend
    build:
      context: .
      dockerfile: Dockerfile.dev
    expose: 
      - 80
    labels:
      traefik.enable: "true"
    env_file:
      - ../.env/.debug.dev
      - ../.env/.jwt.dev
      - ../.env/.host.dev

networks:
  default:
    name: e-files
    external: true